# Generated by Django 4.1 on 2022-08-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heart_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('age', models.FloatField(max_length=255)),
                ('sex', models.FloatField(max_length=255)),
                ('cp', models.FloatField(max_length=255)),
                ('trestbps', models.FloatField(max_length=255)),
                ('chol', models.FloatField(max_length=255)),
                ('thalach', models.FloatField(max_length=255)),
                ('oldpeak', models.FloatField(max_length=255)),
                ('ca', models.FloatField(max_length=255)),
                ('thal', models.FloatField(max_length=255)),
                ('target', models.FloatField(max_length=255)),
            ],
        ),
    ]
